"""add lead reveals

Revision ID: 22b9df7482f5
Revises: 6bc8d5e73d99
Create Date: 2026-09-19 02:57:56.976925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b9df7482f5'
down_revision: Union[str, None] = '6bc8d5e73d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_reveals',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'lead_id', name='uq_reveal_workspace_lead')
    )
    op.create_index(op.f('ix_lead_reveals_lead_id'), 'lead_reveals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_reveals_period'), 'lead_reveals', ['period'], unique=False)
    op.create_index(op.f('ix_lead_reveals_user_id'), 'lead_reveals', ['user_id'], unique=False)
    op.create_index(op.f('ix_lead_reveals_workspace_id'), 'lead_reveals', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_reveals_workspace_id'), table_name='lead_reveals')
    op.drop_index(op.f('ix_lead_reveals_user_id'), table_name='lead_reveals')
    op.drop_index(op.f('ix_lead_reveals_period'), table_name='lead_reveals')
    op.drop_index(op.f('ix_lead_reveals_lead_id'), table_name='lead_reveals')
    op.drop_table('lead_reveals')
    # ### end Alembic commands ###
